# Generated by Django 3.1.4 on 2020-12-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IVNTN_IGNORE_KEY_LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IGNORE_KEY', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='IVNTN_LOGIC_KEY_LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOGIC_KEY', models.CharField(max_length=4000)),
                ('LOGIC_NAME', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='IVNTN_OBJECT_KEY_LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECT_KEY', models.CharField(max_length=4000)),
                ('OBJECT_NAME', models.CharField(max_length=4000)),
                ('OBJECT_MASTER', models.CharField(max_length=4000)),
            ],
        ),
    ]
