# Generated by Django 3.1.4 on 2020-12-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR', '0003_auto_20201209_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='INVTN_EMPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPL_ID', models.CharField(max_length=4000)),
                ('EMPL_NAME', models.CharField(max_length=4000)),
                ('COUNTRY_CD', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='INVTN_EMPL_PAY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPL_ID', models.CharField(max_length=4000)),
                ('SAL', models.IntegerField()),
                ('PAY_PERIOD', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='INVTN_IGNORE_KEY_LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IGNORE_KEY', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='INVTN_LOGIC_KEY_LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOGIC_KEY', models.CharField(max_length=4000)),
                ('LOGIC_NAME', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='INVTN_OBJECT_KEY_LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECT_KEY', models.CharField(max_length=4000)),
                ('OBJECT_NAME', models.CharField(max_length=4000)),
                ('OBJECT_MASTER', models.CharField(max_length=4000)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
