# Generated by Django 3.1.4 on 2020-12-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR', '0007_salaries_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='emp_no',
            field=models.IntegerField(),
        ),
    ]
