# Generated by Django 3.1.4 on 2020-12-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR', '0009_auto_20201213_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_manager',
            name='dept_no',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='dept_manager',
            name='emp_no',
            field=models.IntegerField(),
        ),
    ]
